# Reference: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.yaml.example

logger:
  level: debug
  console: 1

# Query log. Used only for queries with setting log_queries = 1.
query_log:
  database: system
  table: query_log
  partition_by: toYYYYMM(event_date)
  flush_interval_milliseconds: 7500

http_port: 8123
tcp_port: 9000
# Compatibility with MySQL protocol.  ClickHouse will pretend to be MySQL for applications connecting to this port.
mysql_port: 3306

listen_host: "0.0.0.0"
interserver_http_host: clickhouse${REPLICA}
interserver_http_port: 9009

max_connections: 4096
keep_alive_timeout: 3
max_concurrent_queries: 100
uncompressed_cache_size: 8589934592
mark_cache_size: 5368709120

path: /var/lib/clickhouse/
tmp_path: /var/lib/clickhouse/tmp/
user_files_path: /var/lib/clickhouse/user_files/

default_profile: default
default_database: default
timezone: UTC
mlock_executable: true

user_directories:
  users_xml:
    path: users.yaml
  local_directory:
    path: /var/lib/clickhouse/access/

max_server_memory_usage: 0
max_thread_pool_size: 10000
max_server_memory_usage_to_ram_ratio: 0.9
total_memory_profiler_step: 4194304
total_memory_tracker_sample_probability: 0

mmap_cache_size: 1000
compiled_expression_cache_size: 134217728
compiled_expression_cache_elements_size: 10000

remote_servers:
  docker_cluster:
    shard:
      - replica:
          host: clickhouse01
          port: 9000
      - replica:
          host: clickhouse02
          port: 9000
      - replica:
          host: clickhouse03
          port: 9000

zookeeper:
  - node:
      host: zookeeper
      port: 2181

macros:
  shard: ${SHARD}
  replica: clickhouse${REPLICA}

distributed_ddl:
  path: /clickhouse/task_queue/ddl

format_schema_path: /var/lib/clickhouse/format_schemas/
