version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server
    container_name: clickhouse01
    hostname: clickhouse01
    domainname: clickhouse.local
    restart: always
    environment:
      - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config.yaml
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - 8123:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - zookeeper:172.23.0.10
      - clickhouse01:172.23.0.11
      - clickhouse02:172.23.0.12
      - clickhouse03:172.23.0.13
    volumes:
      - ${PWD}/clickhouse01:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse02:
    image: clickhouse/clickhouse-server
    container_name: clickhouse02
    hostname: clickhouse02
    domainname: clickhouse.local
    restart: always
    environment:
      - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config.yaml
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    # ports:
      # - 8123:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - zookeeper:172.23.0.10
      - clickhouse01:172.23.0.11
      - clickhouse02:172.23.0.12
      - clickhouse03:172.23.0.13
    volumes:
      - ${PWD}/clickhouse02:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse03:
    image: clickhouse/clickhouse-server
    container_name: clickhouse03
    hostname: clickhouse03
    domainname: clickhouse.local
    restart: always
    environment:
      - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config.yaml
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    # ports:
      # - 8123:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - zookeeper:172.23.0.10
      - clickhouse01:172.23.0.11
      - clickhouse02:172.23.0.12
      - clickhouse03:172.23.0.13
    volumes:
      - ${PWD}/clickhouse03:/etc/clickhouse-server
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
